version: '3.7'
name: momentso

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DSN: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      APP_BASE_URL: http://localhost:5173
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: mailhog
      SMTP_PASSWORD: mailhog
      SMTP_FROM: "Momentso <test@local>"
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"