name: Build production frontend image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production-frontend
    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/openmomentso/frontend
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Login to image repository
        #if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: frontend
          file: Dockerfile
          build-args: |
            VITE_API_URL=https://api.momentso.com/graphql
          push: true # ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}